pipeline {
  agent any

  parameters {
    string(name: 'action', choices: ['plan', 'apply', 'destroy'], description: 'Terraform action to perform')
  }

  stages {
    stage('Checkout Code') {
      steps {
        git branch: 'master', url: '
      }
    }
    stage('Terraform run'){
      steps{
        bat 'terraform init'
      }
    }
    stage('Terraform Action') {
      when {
        expression { return params.action == 'plan' }
      }
      steps {
        bat "terraform plan"
      }
    }
    stage('Terraform Apply ') {
      when {
        expression { return params.action == 'apply' }
      }
      steps {
        bat "terraform apply"
      }
    }
    
  }
}
